HOME_BTN_IMG_INDEX = 0
UTILITIES_BTN_IMG_INDEX = 1
PAYMENTS_BTN_IMG_INDEX = 2
RECEIPT_BTN_IMG_INDEX = 3
DASHBOARD_BG_IMG_INDEX = 4
UTILITIES_BG_IMG_INDEX = 5
PAYMENTS_BG_IMG_INDEX = 6
RECEIPTS_BG_IMG_INDEX = 7